### ISSUE TITLE
Compile Warnings

### ISSUE THREAD

**Issue by marlonmhm** [nathalis/NCX-LegionLegacy#2]
I have boost_1_60_0, openssl-1.0.0, libssl1.0-dev, but compile on linux ubuntu 19, need an especific version from cmake on generate make, thx

**Comment by nathalis** [comment]
What error generate this code:* cmake ../
-DCMAKE_INSTALL_PREFIX=/root/serverlegion*
*?*


st 13. 5. 2020 o 23:40 marlonmhm <notifications@github.com> napísal(a):

**Comment by marlonmhm** [comment]
cmake compiles ok, but when I run make it compiles but with warnings so it wants to know in linux what was the environment used and what version of smake, c ++ and operating system to replicate it

**Comment by nathalis** [comment]
I used cmake version 3.13.4
and GNU Make 4.2.1
