### ISSUE TITLE
Data Please.

### ISSUE THREAD

**Issue by Ramys** [nathalis/NCX-LegionLegacy#3]
Friend do you have maps, vmaps, mmpas and dbc for donwload?

**Comment by nathalis** [comment]
Yes, I have, but i paid 20$ for that, but I can it provide, if it help you.

**Comment by Ramys** [comment]
Ok , account donate

**Comment by nathalis** [comment]
https://mega.nz/file/JR1BhZyK#mIkDE6ourXFs0V6TWeaQw3zwErSq8dpItawknz5emu0

password to ask by email...
